# Generated by Django 5.0 on 2023-12-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Primary_info',
            fields=[
                ('rank', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('na_sale', models.FloatField()),
                ('eu_sale', models.FloatField()),
                ('jp_sale', models.FloatField()),
                ('other_sale', models.FloatField()),
                ('global_sale', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Secondary_info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=256)),
                ('year', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
                ('publisher', models.CharField(max_length=256)),
            ],
        ),
    ]
